[build]
  publish = "frontend/dist"
  command = "cd frontend && npm ci --legacy-peer-deps && npm run build"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "cd frontend && npm run dev"
  port = 5173
  publish = "frontend/dist" 